### PR TITLE
Use a composition instead of a single image

### PR DESCRIPTION
**Pull request by dnephin**
I don't really expect this to get merged, but I thought I would open a PR to see if there is interest in this setup.

Instead of running a single container with both apache and mysql, run a container for each.  It still needs another container with `volumes_from` for running the `phd`, and another for the arc client.

### CODE REVIEW

**Comment by sils1297** [comment]
I'm not maintainer but this looks cleaner to me at least on first sight.

**Comment by yesnault** [comment]
Great ! I'll merge this after a try and a new README

**Comment by yesnault** [comment]
Hum, there is something broken with mysql-server package.
```
(Reading database ... 9352 files and directories currently installed.)
Preparing to unpack .../mysql-server-5.5_5.5.42-1_amd64.deb ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Configuring mysql-server-5.5
----------------------------

While not mandatory, it is highly recommended that you set a password for the
MySQL administrative "root" user.

If this field is left blank, the password will not be changed.
```

**Comment by dnephin** [comment]
These are just warnings, right?

I dropped `DEBCONF_NONINTERACTIVE_SEEN true` maybe that's why?  would be easy to add that back

**Comment by yesnault** [comment]
No, it's not just warning, it's waiting for something, and fig (yes, I'm on osx...) does't return. I have to Ctrl-C to exit.

I'v tested with 
```
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true
```
but, same result.

**Comment by dnephin** [comment]
That's strange, I was able to build multiple times without any trouble.

I just tried again, and after the text you pasted, I get this (and it proceeds just fine with the rest of the build):

```
New password for the MySQL "root" user: 
Use of uninitialized value $_[1] in join or string at /usr/share/perl5/Debconf/DbDriver/Stack.pm line 111.
Use of uninitialized value $val in substitution (s///) at /usr/share/perl5/Debconf/Format/822.pm line 83, <GEN6> line 1.
Use of uninitialized value $val in concatenation (.) or string at /usr/share/perl5/Debconf/Format/822.pm line 84, <GEN6> line 1.
Unpacking mysql-server-5.5 (5.5.42-1) ...

```

Looking at the dockerfile I don't see any differences between what was being done before and what is happening now (up to that point).

**Comment by yesnault** [comment]
Ok, found.

from : 
```
RUN     DEBIAN_FRONTEND=noninteractive apt-get update
```

To just :
```
RUN apt-get update
```
And add before : 
```
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true
```
LGTM, I'll add some tips in README and merge this after (with fix)

**Pull request merged**
