### PR TITLE
Use ARG variables for the repo commits

### PR DESCRIPTION
**Pull request by jsm**

### CODE REVIEW

**Comment by jsm** [comment]
@yesnault Ping.

Also, if you'd like help maintaining this, I'd be willing to do so.

**Comment by yesnault** [comment]
Merged.

Yes, I'm not phabricator user anymore, and it is not serious to keep something we do serves more ... If you want to help for that, you're welcome :)

**Comment by jsm** [comment]
Cool. Feel free to add me as a maintainer to this project, and I can help review/merge PRs.

**Comment by yesnault** [comment]
Thks, invit sent :)

**Pull request merged**
